### ISSUE TITLE
Builds failing on docs.rs

### ISSUE THREAD

**Issue by QuietMisdreavus** [ohadravid/wmi-rs#11]
Hi! I'm a maintainer for docs.rs, and i noticed that this crate was failing to build on our system. it looks like all your dependencies are gated on Windows builds. While this makes sense for what the crate is doing, it creates a situation where the crate totally fails to build on non-Windows systems, like docs.rs. There are a couple methods to get your docs onto docs.rs:

1\. Tell docs.rs to build your crate for Windows first (recommended)

There's an options section you can add to your Cargo.toml that will configure how docs.rs builds your crate. One of the available options is the "default target" which is the target that docs.rs will build first, as well as the one that will appear when people try to load your crate on docs.rs. Adding the following section to your Cargo.toml will work:

```toml
[package.metadata.docs.rs]
default-target = "x86_64-pc-windows-msvc"
```

2\. Gate your crate contents on `cfg(windows)`

A trick `winapi` pulls to speed up builds on non-Windows systems is to add `#![cfg(windows)]` to the root of the crate to completely wipe out the crate contents unless you're building for Windows. This will help if any user of your crate doesn't gate your crate in their Cargo.toml, since your crate will start "building" on non-Windows platforms, even if it ultimately can't be used. This can be combined with the previous strategy, too.

If it would be easier, i can open a PR to add these to your crate. Thanks!

**Comment by ohadravid** [comment]
Hi!
Thanks! I totally forgot that I can get the docs to docs.rs.
I'll make both changes tomorrow and close the issue afterwards 😁

**Comment by ohadravid** [comment]
Done! It looks awesome.

Thanks a lot 😀
