### ISSUE TITLE
Support for methods in IWbemClassWrapper

### ISSUE THREAD

**Issue by siriux** [ohadravid/wmi-rs#18]
It would be really helpful to get support for methods on IWbemClassWrapper like we have for properties.

I'm thinking of just two methods, a list_methods and exec_method. This would allow to use WMI for than just retrieve information.

**Comment by ohadravid** [comment]
I agree that would be useful. How do you imagine argument passing/return values?

I also wanted to look at com-rs since it might have better ways to handle these kind of operations.

**Comment by siriux** [comment]
I was thinking of something like an array of Variants for the arguments, but I don't know much about the windows API so maybe it's not a good way of doing it.

I just runt into this problem when trying to port a Powershell script to Rust just to see if it could be done.
