### ISSUE TITLE
Possibly migrate from failure to thiserror

### ISSUE THREAD

**Issue by jfro** [ohadravid/wmi-rs#19]
Since failure is deprecated and recommends thiserror & anyhow, it'd be nice to migrate away from it in a future release. 

Failure use in libraries we've found a bit tricky to integrate with our own non-failure error handling at least.

**Comment by ohadravid** [comment]
I agree and will move this library to thiserror, but only in August when I have more time 🙂 
You are also welcome to open a PR since there aren't many custom errors here!

**Comment by jfro** [comment]
will do if I also find some time before you're able!
