### ISSUE TITLE
Query SQLi

### ISSUE THREAD

**Issue by MaulingMonkey** [ohadravid/wmi-rs#26]
These are problematic if `s` contains double quotes:

https://github.com/ohadravid/wmi-rs/blob/b8101bd3cb0ef303dc365d413ff77959eee8b328/src/query.rs#L102-L103

https://docs.microsoft.com/en-us/openspecs/windows_protocols/ms-wmi/6c8a38f4-4ee1-47cb-99f1-b42718a575ce links https://www.dmtf.org/sites/default/files/standards/documents/DSP0004V2.3_final.pdf and seems to imply `\"` should do the trick... or perhaps this conversion should occur when creating the `FilterValue` in the first place?

**Comment by MaulingMonkey** [comment]
`\` also needs to be escaped to `\\` (as pointed out by https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_wql?view=powershell-5.1#using-the-escape-character)

**Comment by ohadravid** [comment]
1. I think the conversion should remain under `build_query` (which frees the consumer of the API to use simple enums with always have the values they expect them to have).
2. Let me know if you intend to work on this, and if so please make sure to add the appropriate tests.

**Comment by MaulingMonkey** [comment]
> 1. I think the conversion should remain under build_query

Works for me!

> 2. Let me know if you intend to work on this, and if so please make sure to add the appropriate tests.

I intend to - although, I need to figure out what WMI classes contain nice test data to test against 😄

**Comment by MaulingMonkey** [comment]
Got a fix for this - I'll create a PR for this once the other one gets merged.

* `Win32_Service.PathName` contains some nice quotes and backslashes to test against.
* `Win32_Product.Caption` *rarely* contains unicode and is expensive as heck to query (23+ seconds!), but I've got one such product installed on my own machine (`PlayStation™Now`) for test coverage.
* Sources of newlines, tabs, or other traditionally-escaped-but-probably-don't-need-to-be values wouldn't hurt if you happen to know of any
