### ISSUE TITLE
unimplemented!() at safearray.rs:125

### ISSUE THREAD

**Issue by yusufpapurcu** [ohadravid/wmi-rs#32]
Hello I'm using this library for accessing remote device's wmi. But project panic's in this point. The reason is `HttpCustomHeaders `behind `IIsWebServerSetting`. This element returning data like this:

```        
"HttpCustomHeaders":  [ "System.Management.ManagementBaseObject"],
```

In this point safearray:125 unimplemented!() panicking. I think we can remove this statements from code. Because unimplemented!() can be a problem in production. Also you can assign me I can handle this.

**Comment by ohadravid** [comment]
I agree that an error should be returned there.
It might also be nice to have an implemention of some serialization for this use case 😄

**Comment by yusufpapurcu** [comment]
I think I must open new issue for this. I searched but I can't find any solution for this use case. I will open new issue maybe someone know 😅

**Comment by yusufpapurcu** [comment]
PR waiting review #33

**Comment by yusufpapurcu** [comment]
Pr #33 closed
