### ISSUE TITLE
COMLibrary always fails on second call

### ISSUE THREAD

**Issue by Guiguiprim** [ohadravid/wmi-rs#37]
The current API is error prone when using `COMLibrary::new()` multiple times.

The following naive code while always fail due to the duplicate security initialization.
The right way of doing it would be to somehow keep track on the security initialization state and use `COMLibrary::without_security()` which is weird and not documented (this is what the internal tests do).

```rust
use wmi::{COMLibrary, WMIResult, WMIConnection};

fn do_something() -> WMIResult<()> {
  let com_con = COMLibrary::new()?;
  let wmi_con = WMIConnection::new(com_con.into())?;
  // ... something
  Ok(())
}

fn main() -> Result<(), Box<dyn std::error::Error>>  {
  // use COM once
  do_something()?;
  // use COM a second time, maybe later, maybe on another thread
  do_something()?;
  Ok(())
}
```

`COMLibrary::new()` could easily treat `RPC_E_TOO_LATE` as not an error.

**Comment by ohadravid** [comment]
The problem I see with the proposed fix is that if the user initialized COM in some other way, the library won't be able to know both if the correct security context has been set and if COM will not be de-initialized while we still hold references to COM-owned data.

I see two solutions here:
1. The original intent: Create `COMLibrary` once, put in an `Rc`, pass that `Rc<COMLibrary>` around. While more "noisy", to me this is IMO the most "correct" way.
2. To use the the unsafe [`WMIConnection::with_initialized_com`](https://docs.rs/wmi/0.9.0/wmi/connection/struct.WMIConnection.html#method.with_initialized_com).

If neither can work in your usecase, could you explain it a bit more?

Thanks for taking the time to open an issue and a PR! 😄

**Comment by vnagarnaik** [comment]
FWIW, I use solution 1 as well.

Another way to solve this is to allow a lazily evaluated singleton value for `COMLibrary`. Add an accessor using `COMLibrary::get()` which would return `Rc<COMLibrary>`. This tells the user that they are free to clone it and reuse as much as needed. If they can't/won't the library prevents duplicate initialization of the instance in `COMLibrary::get()`.

Also, remove `COMLibrary::new()` so that the user cannot construct a second instance of the library

However, I'm not sure if there's another use case which depends on another initialization of `COMLibrary`.

**Comment by Guiguiprim** [comment]
Indeed, doing it this way works.

I guess this could be more documented (perhaps by adding a warning in `COMLibrary::new()` about using it in an `Rc<>` and the risque of calling it twice in an app)

**Comment by bryanlarsen** [comment]
Passing around the WMIConnection was inconvenient for me (cross-platform app that uses it in two very different places), so I tried the Singleton pattern.     Which was a lot more difficult than just putting it into a static OnceCell because the WMIConnection is per-thread.

Here's what I came up with:

```
pub fn wmi_connection() -> Result<Rc<WMIConnection>, WMIError> {
    thread_local!(static WMI_CONNECTION: OnceCell<Rc<WMIConnection>> = OnceCell::new());
    WMI_CONNECTION.with(|wmic| {
        wmic.get_or_try_init(|| {
            let com_connection = COMLibrary::new()?;
            Ok(Rc::new(WMIConnection::new(com_connection)?))
        }).cloned()
    })
}
```

**Comment by bryanlarsen** [comment]
Passing around the WMIConnection was inconvenient for me (cross-platform app that uses it in two different places), so I tried the Singleton pattern.     Which was a lot more difficult than just putting it into a static OnceCell because the WMIConnection is per-thread.

Here's what I came up with:

```
pub fn wmi_connection() -> Result<Rc<WMIConnection>, WMIError> {
    thread_local!(static WMI_CONNECTION: OnceCell<Rc<WMIConnection>> = OnceCell::new());
    WMI_CONNECTION.with(|wmic| {
        wmic.get_or_try_init(|| {
            let com_connection = COMLibrary::new()?;
            Ok(Rc::new(WMIConnection::new(com_connection)?))
        }).cloned()
    })
}
```

**Comment by FantasyTeddy** [comment]
After just stumbling upon this issue while investigating Macchina-CLI/libmacchina#139, the fact that this is not a well documented limitation of `COMLibrary` (that it must be constructed only once and should be reused for every query) should be addressed to prevent others from making the same mistake.

The optimal solution would be to prevent the issue from happening entirely, e.g. by implementing a solution like the one suggested by @vnagarnaik.

**Comment by ohadravid** [comment]
@FantasyTeddy I agree.

I'll accept a PR changing the current `new` impl to ignore `RPC_E_TOO_LATE`.

If someone sets the security context incorrectly, WMI calls will fail in a predictable way so that's not a big issue.

Thanks for talking the time to raise this issue again! 💪

**Comment by FantasyTeddy** [comment]
Thank you for reconsidering and accepting my PR :)
