### ISSUE TITLE
how to update the deseralized object's member functions?

### ISSUE THREAD

**Issue by qingmo** [ohadravid/wmi-rs#44]
such as Win32 _ NetworkAdapterConfiguration
after raw_query get vec<>. how can i use those structure to execute **EnableStatic** functions?

**Comment by ohadravid** [comment]
Hi @qingmo,

This is similar to #18.
Currently, this crate doesn't have a way to do this, but I agree that it's something that would be very useful.

You are welcome to try implementing it yourself and open a PR, but if you want a "dirty" solution you can probably work directly with `exec_query_native_wrapper` and implement something like `IWbemClassWrapper ::list_properties`.

**Comment by qingmo** [comment]
thank you for you suggestion.
