### ISSUE TITLE
 I can't communicate in "tauri"

### ISSUE THREAD

**Issue by ajuner** [ohadravid/wmi-rs#48]
Hello, I just started with rust, I can't communicate in "tauri", I hope to get your help

![image](https://user-images.githubusercontent.com/53512912/160868528-fbf08f33-2ada-4283-bad4-da002b95ac0b.png)

**Comment by Zomatree** [comment]
Hey, did you find a fix for this issue? Im having the same issue and have not found a solution to it yet.

**Comment by ajuner** [comment]
another thread to get it

**Comment by tance77** [comment]
@ajuner Can you show us an example of how you solved the issue with another thread?

**Comment by tance77** [comment]
Figured this out. It's specific to Tauri setting this function. https://learn.microsoft.com/en-us/windows/win32/api/combaseapi/nf-combaseapi-coinitializesecurity

```rs
//Assuming Tauri Has Already Initialized coinitializesecurity then we can tell the Com Library we don't need to do this with this function. Don't do this if coinitializesecurity has not been initialized.
  let com_connection = unsafe {COMLibrary::assume_initialized()}; 
  let wmi_connection = WMIConnection::new(com_connection.into()).expect("Failed to connect to WMI");
  let result: Vec<Win32_ComputerSystemProduct> = wmi_connection.query().unwrap();
  ```

**Comment by lucacastelnuovo** [comment]
@tance77 Thank you so much!
