### ISSUE TITLE
Question: Handling Variants & Deserialization

### ISSUE THREAD

**Issue by WalrusSoup** [ohadravid/wmi-rs#49]
Hello!

I am struggling to work with some of the types. 

```rs
struct Win32_Process {
    CommandLine: Variant, // This line here only works as type Variant
    Name: String
}
```

When querying for processes, the `CommandLine` type according to the [docs located here](https://docs.microsoft.com/en-us/windows/win32/cimwin32prov/win32-process) say that it should be of type `String`, however, when running it with string, `Serde` throws a JSON error that says it cannot `invalid type: Option value, expected a string`. 

This makes sense because this can sometimes be null (for svchost, etc). However, I cannot seem to get the underlying value to be a string?

edit: nevermind, just as I posted this, I figured it out.

```rs
let path : String = process.CommandLine.try_into().unwrap_or("".to_string());
```

**Comment by ohadravid** [comment]
You should also be able to use 
```
struct Win32_Process {
    CommandLine: Option<String>,
    Name: String
}
```
