### ISSUE TITLE
WMIConnection::create_services hangs indefinitely calling IWbemLocator::ConnectServer

### ISSUE THREAD

**Issue by Soul85** [ohadravid/wmi-rs#56]
Hi,

I have identified an issue within `WMIConnection::create_services` where it is passing 0 for `lSecurityFlags` when calling `IWbemLocator::ConnectServer`. [According to Microsoft docs](https://docs.microsoft.com/en-us/windows/win32/api/wbemcli/nf-wbemcli-iwbemlocator-connectserver), this causes the API to attempt to connect indefinitely, leading to moments where a simple query will halt the entire program.

I suggest the default for `lSecurityFlags` be changed to [WBEM_FLAG_CONNECT_USE_MAX_WAIT](https://docs.microsoft.com/en-us/windows/win32/api/wbemcli/nf-wbemcli-iwbemlocator-connectserver?redirectedfrom=MSDN#wbem_flag_connect_use_max_wait-128-0x80) and an unsafe option be given to wait indefinitely to prevent future cases such as this.

**Comment by ohadravid** [comment]
Sound good to me. I don't think there's a use case for the indefinite wait so we don't need to support it at all IMO (and it wouldn't be unsafe anyway as far as I can tell).

Do you want to open a PR with this change?

Thanks for taking the time to report this!

**Comment by Soul85** [comment]
If you don't mind making the change yourself that'd be great. I mostly operate off of my work device unfortunately!
