### ISSUE TITLE
Migrate from winapi to windows-rs

### ISSUE THREAD

**Issue by vthib** [ohadravid/wmi-rs#67]
`windows` and `windows-sys` are new crates that are officially developped and supported by Microsoft (and quite actively maintained), while `winapi` looks unmaintained and is currently being phased out and replaced by those windows crates in many projects.

I have done so locally to check how feasible it would be and it brings a lot of simplification to the code:

- existing BSTR wrapper, no need for a custom one
- automatic handling of Clone & Drop for all WBEM types, so no need to use AddRef/Release by hand
- existing helpers for COM interfaces, with casting between interfaces properly handled and the QuerySink impl being available
- and more

Would you be open to a `winapi` => `windows` migration? I can push a PR doing this migration and we can discuss it more in details in it

**Comment by ohadravid** [comment]
That would be awesome! Go ahead @vthib

**Comment by poliorcetics** [comment]
@ohadravid In the commit history I see the version was bumped after the merge of #68 but the release on crates.io doesn't seem to include it ?

```
$ cargo tree -p wmi --target all

wmi v0.11.5
(cut)
└── winapi v0.3.9
    ├── winapi-i686-pc-windows-gnu v0.4.0
    └── winapi-x86_64-pc-windows-gnu v0.4.0
```

**Comment by poliorcetics** [comment]
Oh ignore what I said, i didn't see the 0.12, sorry for the noise
