### ISSUE TITLE
Update to more recent windows-rs?

### ISSUE THREAD

**Issue by ydirson** [ohadravid/wmi-rs#88]
Are there any plans to update to windows-rs 0.52 or newer?

From [this discussion](https://github.com/microsoft/windows-rs/issues/2751#issuecomment-1892194256) it looks like 0.52 (or possibly unreleased 0.53) would be required to get ExecMethod to run...

**Comment by ohadravid** [comment]
Should be pretty straightforward.

I might have time to get to this later this month, but you are welcome to open a PR if you have the time 🙌🏻

**Comment by ydirson** [comment]
Great, thanks!
Unfortunately `windows-rs` APIs continue to move a lot: I need 60f9e456952f for BSTR variants, but `wmi-rs` apparently needs quite a few more adjustments to work with that new snapshot (variants changed again), and https://github.com/microsoft/windows-rs/pull/2812 since then brought even more API changes.  I guess I'll continue for now with my direct use of `windows-rs`, and when 0.53 gets out we should be able to sync again.
